import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "../app/globals.css";
import { SoloConsole } from "../app/solo-console";
import { ExpeditionConsole } from "../app/expedition-console";
import { GameConsole } from "../app/game-console";

type Mode="menu"|"solo"|"expedition"|"gm";
const readMode=():Mode=>{const value=window.location.hash.replace("#","");return value==="solo"||value==="expedition"||value==="gm"?value:"menu";};
const modes=[
  {number:"01",eyebrow:"Один против метро",title:"Соло-экспедиция",text:"Выберите одного персонажа. Остальные одиннадцать путников станут ботами и будут соревноваться с вами за место в Полисе.",meta:"1 человек · 11 ботов",hash:"#solo",action:"Выбрать персонажа"},
  {number:"02",eyebrow:"Компания без ведущей",title:"Люди и боты",text:"От двух до двенадцати живых игроков на одном игровом экране. Пустые места займут боты.",meta:"2–12 человек · остальные боты",hash:"#expedition",action:"Собрать компанию"},
  {number:"03",eyebrow:"Большая ролевая партия",title:"Пульт ведущей",text:"Полная карта, тоннели, NPC, кризис, часы и управление большой партией. Работает автономно прямо в браузере.",meta:"12 человек · 1 ведущая",hash:"#gm",action:"Открыть пульт"},
] as const;
const guides={
  solo:{kicker:"Режим 01 · коротко",title:"Как пройти экспедицию",steps:["Выберите персонажа — личная цель откроется после старта.","Каждый раунд решайте: остаться на станции или пройти один тоннель.","На станции добывается ресурс; в тоннеле может выпасть испытание или тихий проход.","Решайте испытания предметом, патронами, осторожным действием или риском.","Доберитесь до Полиса раньше других путников. Потеря четырёх конечностей означает гибель."]},
  expedition:{kicker:"Режим 02 · коротко",title:"Как играть компанией",steps:["Укажите число живых игроков, выберите каждому роль и старт. Остальных поведут боты.","Люди принимают решения по очереди; после последнего человека ходят боты.","Можно идти разными маршрутами или выбрать один тоннель: следующий попутчик пройдёт его безопаснее.","Остановка даёт ресурс станции. Кордоны оплачиваются патронами.","Общая задача — добраться до Полиса, не потеряв все четыре конечности."]},
  gm:{kicker:"Режим 03 · коротко",title:"Что делает ведущая",steps:["Начните с вкладки «Карта»: проверьте позиции игроков, тоннели и караваны.","Игроки последовательно объявляют решения, а вы открываете и разрешаете их ход.","Используйте «Колесо» для испытаний, «NPC» для найма и «Игроки» для ранений и ресурсов.","После хода всех групп завершите мировой раунд: сдвиньте время, караваны и при необходимости Чёрное нечто.","Пульт сохраняется в этом браузере. Перед настоящей партией проведите один короткий тестовый раунд."]},
} as const;
function ModeMenu(){return <main className="mode-select-shell"><header className="mode-select-head"><div><span>Москва · 2030</span><b>Голоса под Москвой</b></div><em>Выберите формат партии</em></header><section className="mode-select-hero"><p className="pixel-kicker">Три способа услышать голоса</p><h1>Сколько вас<br/><span>спустилось?</span></h1><p>Карта одна. Правила пути меняются в зависимости от того, кто сидит по другую сторону экрана.</p></section><section className="mode-card-grid">{modes.map(mode=><a className="mode-card" href={mode.hash} key={mode.hash}><div><span>{mode.number}</span><small>{mode.eyebrow}</small></div><h2>{mode.title}</h2><p>{mode.text}</p><footer><b>{mode.meta}</b><strong>{mode.action} →</strong></footer></a>)}</section><footer className="mode-select-footer"><span>GitHub-сборка · без входа в ChatGPT</span><i>◉ Патроны · 🐫 Караваны · 4 конечности</i></footer></main>}
function ModeGuide({mode,onClose}:{mode:Exclude<Mode,"menu">;onClose:()=>void}){const guide=guides[mode];return <div className="mode-guide-backdrop" role="dialog" aria-modal="true" aria-labelledby="mode-guide-title"><article className="mode-guide-card"><span>{guide.kicker}</span><h2 id="mode-guide-title">{guide.title}</h2><ol>{guide.steps.map((step,index)=><li key={step}><b>{String(index+1).padStart(2,"0")}</b><p>{step}</p></li>)}</ol><button className="pixel-primary" onClick={onClose}>Понятно, начать →</button><small>Эту карточку всегда можно вернуть кнопкой «Правила».</small></article></div>}
function App(){const [mode,setMode]=useState<Mode>(readMode);const [guideOpen,setGuideOpen]=useState(false);useEffect(()=>{const change=()=>setMode(readMode());const intercept=(event:MouseEvent)=>{const anchor=(event.target as HTMLElement).closest("a");if(anchor?.getAttribute("href")==="/"){event.preventDefault();window.location.hash="";}};window.addEventListener("hashchange",change);document.addEventListener("click",intercept);return()=>{window.removeEventListener("hashchange",change);document.removeEventListener("click",intercept);};},[]);useEffect(()=>{if(mode==="menu"){setGuideOpen(false);return;}setGuideOpen(localStorage.getItem(`golosa-guide-${mode}`)!=="seen");},[mode]);const closeGuide=()=>{if(mode!=="menu")localStorage.setItem(`golosa-guide-${mode}`,"seen");setGuideOpen(false);};if(mode==="menu")return <ModeMenu/>;const game=mode==="solo"?<SoloConsole/>:mode==="expedition"?<ExpeditionConsole/>:<GameConsole/>;return <><a className="github-mode-back" href="#">← Режимы</a><button className="github-rules-open" onClick={()=>setGuideOpen(true)}>Правила</button>{game}{guideOpen&&<ModeGuide mode={mode} onClose={closeGuide}/>}</>;}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
